repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        exclude: ((?:data|experiments|model_results|venv|frontend))
        language_version: python3.10.8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args:
          [
            '--exclude="((?:data|experiments|model_results|venv|frontend))"',
            "--ignore-missing-imports",
            "--install-types",
            "--non-interactive"
          ]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "--exit-zero",
            "--output-format=text",
            "--recursive=true",
            "--disable=C0114,C0115,C0116,F0010,E0401,R0914,R1702,R1735,R0912,R0915,R0913,R0903,C0413",
            '--ignore-patterns="((?:data|experiments|model_results|venv|frontend))"',
          ]
