[tool.black]
line-length = 128
target-version = ['py310']

[tool.ruff]
line-length = 128
target-version = 'py310'
ignore-init-module-imports = true
ignore = ['E203', 'E501']
# E203: See https://github.com/PyCQA/pycodestyle/issues/373
# E501: Disable line length error
